---
name: BlockGenerator
version: 0.1.6
main: NhanAZ\BlockGenerator\Main
api: 5.0.0

virions:
  - NhanAZ/libBedrock

website: https://github.com/NhanAZ
description: Random blocks generator with water and fences.
author: NhanAZ
...
